/*
 * httpbin.org
 * A simple HTTP Request & Response Service.<br/> <br/> <b>Run locally: </b> <code>$ docker run -p 80:80 kennethreitz/httpbin</code>
 *
 * The version of the OpenAPI document: 0.9.2
 * Contact: me@kennethreitz.org
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.api;

import com.konfigthis.client.ApiException;
import com.konfigthis.client.ApiClient;
import com.konfigthis.client.ApiException;
import com.konfigthis.client.Configuration;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeAll;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for AnythingApi
 */
@Disabled
public class AnythingApiTest {

    private static AnythingApi api;

    
    @BeforeAll
    public static void beforeClass() {
        ApiClient apiClient = Configuration.getDefaultApiClient();
        api = new AnythingApi(apiClient);
    }

    /**
     * Returns anything passed in request data.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getAnythingTest() throws ApiException {
        api.getAnything()
                .execute();
        // TODO: test validations
    }

    /**
     * Returns anything passed in request data.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getDataTest() throws ApiException {
        api.getData()
                .execute();
        // TODO: test validations
    }

    /**
     * Returns anything passed in request data.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getData_0Test() throws ApiException {
        api.getData_0()
                .execute();
        // TODO: test validations
    }

    /**
     * Returns anything passed in request data.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getData_1Test() throws ApiException {
        api.getData_1()
                .execute();
        // TODO: test validations
    }

    /**
     * Returns anything passed in request data.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getData_2Test() throws ApiException {
        api.getData_2()
                .execute();
        // TODO: test validations
    }

    /**
     * Returns anything passed in request data.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getPassedDataTest() throws ApiException {
        api.getPassedData()
                .execute();
        // TODO: test validations
    }

    /**
     * Returns anything passed in request data.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getPassedData_0Test() throws ApiException {
        api.getPassedData_0()
                .execute();
        // TODO: test validations
    }

    /**
     * Returns anything passed in request data.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void postRequestDataTest() throws ApiException {
        api.postRequestData()
                .execute();
        // TODO: test validations
    }

    /**
     * Returns anything passed in request data.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void putRequestDataTest() throws ApiException {
        api.putRequestData()
                .execute();
        // TODO: test validations
    }

    /**
     * Returns anything passed in request data.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void returnDataTest() throws ApiException {
        api.returnData()
                .execute();
        // TODO: test validations
    }

    /**
     * Returns anything passed in request data.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void returnRequestDataTest() throws ApiException {
        api.returnRequestData()
                .execute();
        // TODO: test validations
    }

    /**
     * Returns anything passed in request data.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void updateAnythingDataTest() throws ApiException {
        api.updateAnythingData()
                .execute();
        // TODO: test validations
    }

}
