/*
 * httpbin.org
 * A simple HTTP Request & Response Service.<br/> <br/> <b>Run locally: </b> <code>$ docker run -p 80:80 kennethreitz/httpbin</code>
 *
 * The version of the OpenAPI document: 0.9.2
 * Contact: me@kennethreitz.org
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.api;

import com.konfigthis.client.ApiException;
import com.konfigthis.client.ApiClient;
import com.konfigthis.client.ApiException;
import com.konfigthis.client.Configuration;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeAll;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for HttpMethodsApi
 */
@Disabled
public class HttpMethodsApiTest {

    private static HttpMethodsApi api;

    
    @BeforeAll
    public static void beforeClass() {
        ApiClient apiClient = Configuration.getDefaultApiClient();
        api = new HttpMethodsApi(apiClient);
    }

    /**
     * The request&#39;s DELETE parameters.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void deleteRequestParametersTest() throws ApiException {
        api.deleteRequestParameters()
                .execute();
        // TODO: test validations
    }

    /**
     * The request&#39;s POST parameters.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void postRequestParametersTest() throws ApiException {
        api.postRequestParameters()
                .execute();
        // TODO: test validations
    }

    /**
     * The request&#39;s PUT parameters.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void putRequestParametersTest() throws ApiException {
        api.putRequestParameters()
                .execute();
        // TODO: test validations
    }

    /**
     * The request&#39;s query parameters.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void requestQueryParametersGetTest() throws ApiException {
        api.requestQueryParametersGet()
                .execute();
        // TODO: test validations
    }

    /**
     * The request&#39;s PATCH parameters.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void updateRequestParametersTest() throws ApiException {
        api.updateRequestParameters()
                .execute();
        // TODO: test validations
    }

}
