/*
 * httpbin.org
 * A simple HTTP Request & Response Service.<br/> <br/> <b>Run locally: </b> <code>$ docker run -p 80:80 kennethreitz/httpbin</code>
 *
 * The version of the OpenAPI document: 0.9.2
 * Contact: me@kennethreitz.org
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.api;

import com.konfigthis.client.ApiException;
import com.konfigthis.client.ApiClient;
import com.konfigthis.client.ApiException;
import com.konfigthis.client.Configuration;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeAll;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ImagesApi
 */
@Disabled
public class ImagesApiTest {

    private static ImagesApi api;

    
    @BeforeAll
    public static void beforeClass() {
        ApiClient apiClient = Configuration.getDefaultApiClient();
        api = new ImagesApi(apiClient);
    }

    /**
     * Returns a simple image of the type suggest by the Accept header.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getByAcceptHeaderTest() throws ApiException {
        api.getByAcceptHeader()
                .execute();
        // TODO: test validations
    }

    /**
     * Returns a simple JPEG image.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getJpegImageTest() throws ApiException {
        api.getJpegImage()
                .execute();
        // TODO: test validations
    }

    /**
     * Returns a simple PNG image.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getPngImageTest() throws ApiException {
        api.getPngImage()
                .execute();
        // TODO: test validations
    }

    /**
     * Returns a simple SVG image.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getSvgImageTest() throws ApiException {
        api.getSvgImage()
                .execute();
        // TODO: test validations
    }

    /**
     * Returns a simple WEBP image.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getWebpImageTest() throws ApiException {
        api.getWebpImage()
                .execute();
        // TODO: test validations
    }

}
