/*
 * httpbin.org
 * A simple HTTP Request & Response Service.<br/> <br/> <b>Run locally: </b> <code>$ docker run -p 80:80 kennethreitz/httpbin</code>
 *
 * The version of the OpenAPI document: 0.9.2
 * Contact: me@kennethreitz.org
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.api;

import com.konfigthis.client.ApiException;
import com.konfigthis.client.ApiClient;
import com.konfigthis.client.ApiException;
import com.konfigthis.client.Configuration;
import com.konfigthis.client.model.RedirectsToGivenUrlPostRequest;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeAll;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for RedirectsApi
 */
@Disabled
public class RedirectsApiTest {

    private static RedirectsApi api;

    
    @BeforeAll
    public static void beforeClass() {
        ApiClient apiClient = Configuration.getDefaultApiClient();
        api = new RedirectsApi(apiClient);
    }

    /**
     * Absolutely 302 Redirects n times.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void absolutelyRedirectsNTest() throws ApiException {
        Integer n = null;
        api.absolutelyRedirectsN(n)
                .execute();
        // TODO: test validations
    }

    /**
     * 302 Redirects n times.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void call302redirectsNTest() throws ApiException {
        Integer n = null;
        api.call302redirectsN(n)
                .execute();
        // TODO: test validations
    }

    /**
     * 302/3XX Redirects to the given URL.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void givenUrlPutRedirectTest() throws ApiException {
        String url = null;
        Integer statusCode = null;
        api.givenUrlPutRedirect(url)
                .statusCode(statusCode)
                .execute();
        // TODO: test validations
    }

    /**
     * Relatively 302 Redirects n times.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void relatively302RedirectsNTest() throws ApiException {
        Integer n = null;
        api.relatively302RedirectsN(n)
                .execute();
        // TODO: test validations
    }

    /**
     * 302/3XX Redirects to the given URL.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void toGivenUrlDeleteTest() throws ApiException {
        api.toGivenUrlDelete()
                .execute();
        // TODO: test validations
    }

    /**
     * 302/3XX Redirects to the given URL.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void toGivenUrlGetTest() throws ApiException {
        String url = null;
        Integer statusCode = null;
        api.toGivenUrlGet(url)
                .statusCode(statusCode)
                .execute();
        // TODO: test validations
    }

    /**
     * 302/3XX Redirects to the given URL.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void toGivenUrlPatchTest() throws ApiException {
        api.toGivenUrlPatch()
                .execute();
        // TODO: test validations
    }

    /**
     * 302/3XX Redirects to the given URL.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void toGivenUrlPostTest() throws ApiException {
        String url = null;
        Integer statusCode = null;
        api.toGivenUrlPost(url)
                .statusCode(statusCode)
                .execute();
        // TODO: test validations
    }

    /**
     * 302/3XX Redirects to the given URL.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void toGivenUrlTraceTest() throws ApiException {
        api.toGivenUrlTrace()
                .execute();
        // TODO: test validations
    }

}
