/*
 * httpbin.org
 * A simple HTTP Request & Response Service.<br/> <br/> <b>Run locally: </b> <code>$ docker run -p 80:80 kennethreitz/httpbin</code>
 *
 * The version of the OpenAPI document: 0.9.2
 * Contact: me@kennethreitz.org
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.api;

import com.konfigthis.client.ApiException;
import com.konfigthis.client.ApiClient;
import com.konfigthis.client.ApiException;
import com.konfigthis.client.Configuration;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeAll;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for RequestInspectionApi
 */
@Disabled
public class RequestInspectionApiTest {

    private static RequestInspectionApi api;

    
    @BeforeAll
    public static void beforeClass() {
        ApiClient apiClient = Configuration.getDefaultApiClient();
        api = new RequestInspectionApi(apiClient);
    }

    /**
     * Return the incoming request&#39;s HTTP headers.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void incomingHeadersGetTest() throws ApiException {
        api.incomingHeadersGet()
                .execute();
        // TODO: test validations
    }

    /**
     * Returns the requester&#39;s IP Address.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void ipAddressGetTest() throws ApiException {
        api.ipAddressGet()
                .execute();
        // TODO: test validations
    }

    /**
     * Return the incoming requests&#39;s User-Agent header.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void userAgentGetTest() throws ApiException {
        api.userAgentGet()
                .execute();
        // TODO: test validations
    }

}
