/*
 * httpbin.org
 * A simple HTTP Request & Response Service.<br/> <br/> <b>Run locally: </b> <code>$ docker run -p 80:80 kennethreitz/httpbin</code>
 *
 * The version of the OpenAPI document: 0.9.2
 * Contact: me@kennethreitz.org
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.api;

import com.konfigthis.client.ApiException;
import com.konfigthis.client.ApiClient;
import com.konfigthis.client.ApiException;
import com.konfigthis.client.Configuration;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeAll;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ResponseInspectionApi
 */
@Disabled
public class ResponseInspectionApiTest {

    private static ResponseInspectionApi api;

    
    @BeforeAll
    public static void beforeClass() {
        ApiClient apiClient = Configuration.getDefaultApiClient();
        api = new ResponseInspectionApi(apiClient);
    }

    /**
     * Sets a Cache-Control header for n seconds.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void cacheControlSetTest() throws ApiException {
        Integer value = null;
        api.cacheControlSet(value)
                .execute();
        // TODO: test validations
    }

    /**
     * Returns a set of response headers from the query string.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getResponseHeadersTest() throws ApiException {
        Map<String, String> freeform = null;
        api.getResponseHeaders()
                .freeform(freeform)
                .execute();
        // TODO: test validations
    }

    /**
     * Returns a 304 if an If-Modified-Since header or If-None-Match is present. Returns the same as a GET otherwise.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void notModifiedGetTest() throws ApiException {
        String ifModifiedSince = null;
        String ifNoneMatch = null;
        api.notModifiedGet()
                .ifModifiedSince(ifModifiedSince)
                .ifNoneMatch(ifNoneMatch)
                .execute();
        // TODO: test validations
    }

    /**
     * Returns a set of response headers from the query string.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void queryHeadersGetTest() throws ApiException {
        Map<String, String> freeform = null;
        api.queryHeadersGet()
                .freeform(freeform)
                .execute();
        // TODO: test validations
    }

    /**
     * Assumes the resource has the given etag and responds to If-None-Match and If-Match headers appropriately.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void resourceInspectionGetTest() throws ApiException {
        String ifNoneMatch = null;
        String ifMatch = null;
        api.resourceInspectionGet()
                .ifNoneMatch(ifNoneMatch)
                .ifMatch(ifMatch)
                .execute();
        // TODO: test validations
    }

}
