/*
 * httpbin.org
 * A simple HTTP Request & Response Service.<br/> <br/> <b>Run locally: </b> <code>$ docker run -p 80:80 kennethreitz/httpbin</code>
 *
 * The version of the OpenAPI document: 0.9.2
 * Contact: me@kennethreitz.org
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.api;

import com.konfigthis.client.ApiException;
import com.konfigthis.client.ApiClient;
import com.konfigthis.client.ApiException;
import com.konfigthis.client.Configuration;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeAll;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for StatusCodesApi
 */
@Disabled
public class StatusCodesApiTest {

    private static StatusCodesApi api;

    
    @BeforeAll
    public static void beforeClass() {
        ApiClient apiClient = Configuration.getDefaultApiClient();
        api = new StatusCodesApi(apiClient);
    }

    /**
     * Return status code or random status code if more than one are given
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void returnRandomCodeTest() throws ApiException {
        String codes = null;
        api.returnRandomCode(codes)
                .execute();
        // TODO: test validations
    }

    /**
     * Return status code or random status code if more than one are given
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void returnRandomCode_0Test() throws ApiException {
        String codes = null;
        api.returnRandomCode_0(codes)
                .execute();
        // TODO: test validations
    }

    /**
     * Return status code or random status code if more than one are given
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void returnRandomCode_1Test() throws ApiException {
        String codes = null;
        api.returnRandomCode_1(codes)
                .execute();
        // TODO: test validations
    }

    /**
     * Return status code or random status code if more than one are given
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void returnRandomCode_2Test() throws ApiException {
        String codes = null;
        api.returnRandomCode_2(codes)
                .execute();
        // TODO: test validations
    }

    /**
     * Return status code or random status code if more than one are given
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void returnRandomCode_3Test() throws ApiException {
        String codes = null;
        api.returnRandomCode_3(codes)
                .execute();
        // TODO: test validations
    }

    /**
     * Return status code or random status code if more than one are given
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void returnRandomCode_4Test() throws ApiException {
        String codes = null;
        api.returnRandomCode_4(codes)
                .execute();
        // TODO: test validations
    }

}
